/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pgv_multihilos13;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.Timer;

/**
 *
 * @author Cedric Christoph
 */
public class Interfaz extends javax.swing.JFrame {

    Carrera carrera;
    ArrayList<Vehiculo> vehiculos;
    
    
    public Interfaz() {
        initComponents();
        carrera = null;
        vehiculos = new ArrayList<>();
    }

    
    private JPanel getVehiculoBox(Vehiculo vehiculo) {
        JProgressBar progress = new JProgressBar();
        progress.setMaximum(carrera.getRecorrido().getDistanciaTotal());
        progress.setMinimumSize(new Dimension(150, 15));
        progress.setPreferredSize(new Dimension(150, 15));
        JLabel labelName = new JLabel(vehiculo.getMatricula() + " " + vehiculo.getMarca());
        labelName.setMinimumSize(new Dimension(100, 20));
        labelName.setPreferredSize(new Dimension(100, 20));
        
        
        JPanel container = new JPanel();
        container.setMinimumSize(new Dimension(200, 100));
        container.setPreferredSize(new Dimension(200, 100));
        container.setLayout(new BoxLayout(container, BoxLayout.PAGE_AXIS));
        container.add(labelName);
        container.add(progress);
        container.setVisible(true);
        JPanel panel = new JPanel();
        panel.setMinimumSize(new Dimension(250, 150));
        panel.setPreferredSize(new Dimension(250, 150));
        panel.add(container);
        panel.setVisible(true);
        return panel;
        
        
//        javax.swing.GroupLayout panelVehiculoTemplateLayout = new javax.swing.GroupLayout(panel);
//        panel.setLayout(panelVehiculoTemplateLayout);
//        panelVehiculoTemplateLayout.setHorizontalGroup(
//            panelVehiculoTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(panelVehiculoTemplateLayout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(panelVehiculoTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(labelName)
//                    .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addContainerGap())
//        );
//        panelVehiculoTemplateLayout.setVerticalGroup(
//            panelVehiculoTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(panelVehiculoTemplateLayout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(panel)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVehiculos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVehiculos = new javax.swing.JTextArea();
        jmenu = new javax.swing.JMenuBar();
        Carrera = new javax.swing.JMenu();
        menuCrearCarrera = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuAddMoto = new javax.swing.JMenuItem();
        menuAddCoche = new javax.swing.JMenuItem();
        menuAddGuagua = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuIniciarCarrera = new javax.swing.JMenuItem();
        close = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelVehiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelVehiculos.setAutoscrolls(true);

        javax.swing.GroupLayout panelVehiculosLayout = new javax.swing.GroupLayout(panelVehiculos);
        panelVehiculos.setLayout(panelVehiculosLayout);
        panelVehiculosLayout.setHorizontalGroup(
            panelVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        panelVehiculosLayout.setVerticalGroup(
            panelVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        txtVehiculos.setEditable(false);
        txtVehiculos.setBackground(new java.awt.Color(238, 238, 238));
        txtVehiculos.setColumns(20);
        txtVehiculos.setRows(5);
        jScrollPane2.setViewportView(txtVehiculos);

        Carrera.setText("Carrera");

        menuCrearCarrera.setText("Nueva carrera");
        menuCrearCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearCarreraActionPerformed(evt);
            }
        });
        Carrera.add(menuCrearCarrera);
        Carrera.add(jSeparator1);

        menuAddMoto.setText("Nueva moto");
        menuAddMoto.setToolTipText("");
        menuAddMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddMotoActionPerformed(evt);
            }
        });
        Carrera.add(menuAddMoto);

        menuAddCoche.setText("Nuevo coche");
        menuAddCoche.setToolTipText("");
        Carrera.add(menuAddCoche);

        menuAddGuagua.setText("Nueva guagua");
        menuAddGuagua.setToolTipText("");
        Carrera.add(menuAddGuagua);
        Carrera.add(jSeparator2);

        menuIniciarCarrera.setText("Iniciar carrera");
        menuIniciarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarCarreraActionPerformed(evt);
            }
        });
        Carrera.add(menuIniciarCarrera);

        jmenu.add(Carrera);

        close.setText("Cerrar");
        jmenu.add(close);

        setJMenuBar(jmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(panelVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(panelVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCrearCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearCarreraActionPerformed
        carrera = new Carrera();
        Recorrido r = new Recorrido(1000, 5);
        carrera.setRecorrido(r);
    }//GEN-LAST:event_menuCrearCarreraActionPerformed

    private void menuAddMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddMotoActionPerformed
        addVehiculo(new Moto(("Moto " + (vehiculos.size()+1)), "MARCA", Vehiculo.VEHICULO_POTENTE));
    }//GEN-LAST:event_menuAddMotoActionPerformed

    private void menuIniciarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarCarreraActionPerformed
        carrera.setVehiculos(vehiculos);
        start();
    }//GEN-LAST:event_menuIniciarCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
        
    }
    
    private void addVehiculo(Vehiculo v) {
        vehiculos.add(v);
        txtVehiculos.setText(txtVehiculos.getText() + v.getMarca() + " " + v.getMatricula() + "\n");
        panelVehiculos.add(getVehiculoBox(v));
        System.out.println("Vehiculo creado");
        for (Component c : panelVehiculos.getComponents()) {
            System.out.println(c.toString());
        }
        panelVehiculos.revalidate();
        panelVehiculos.repaint();
    }
    
    private void start() {
        
        carrera.start();
        
        final Timer t = new Timer(50, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (carrera.carreraFinalizada == false)
                {
                    for (int indexVehiculo = 0; indexVehiculo < vehiculos.size(); indexVehiculo++) {
                        JProgressBar progress = null;
                        if (indexVehiculo == 0)
                            progress = (JProgressBar) panelVehiculos.getComponent(1);
                        else
                            progress = (JProgressBar) panelVehiculos.getComponent(indexVehiculo+2);
                        progress.setValue((int) vehiculos.get(indexVehiculo).getDistanciaRecorrida());
                    }
                }
            }

        });
        t.start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Carrera;
    private javax.swing.JMenu close;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar jmenu;
    private javax.swing.JMenuItem menuAddCoche;
    private javax.swing.JMenuItem menuAddGuagua;
    private javax.swing.JMenuItem menuAddMoto;
    private javax.swing.JMenuItem menuCrearCarrera;
    private javax.swing.JMenuItem menuIniciarCarrera;
    private javax.swing.JPanel panelVehiculos;
    private javax.swing.JTextArea txtVehiculos;
    // End of variables declaration//GEN-END:variables
}
